services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    labels:
      - service=redis-keystore

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env 
    depends_on:
      - redis
    labels:
      - service=url-shortener
