openapi: 3.0.0
info:
  title: URL Shortener API
  version: 1.0.0
  description: API for URL shortening and user authentication via Google.

paths:
  /api/auth:
    get:
      tags:
        - Authentication
      summary: Initiates Google Sign-In
      operationId: signIn
      responses:
        '200':
          description: Returns the Google sign-in URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: "https://accounts.google.com/o/oauth2/v2/auth?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&response_type=code&scope=profile email"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error message"
  /api/shorten:
    post:
      tags:
        - URL Shortener
      summary: Create a short URL
      operationId: createShortURL
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                long_url:
                  type: string
                  example: "https://example.com"
                topic:
                  type: string
                  example: "Social Media"
                custom_alias:
                  type: string
                  example: "shorty"
      responses:
        '201':
          description: Short URL created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  url_id:
                    type: integer
                    example: 1
                  long_url:
                    type: string
                    example: "https://example.com"
                  short_url:
                    type: string
                    example: "http://short.url/shorty"
        '401':
          description: Unauthorized Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized request"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Alias length should be 6."
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal Server Error"

  /api/shorten/{alias}:
    get:
      tags:
        - URL Shortener
      summary: Redirect to the long URL
      operationId: redirectToLongURL
      parameters:
        - name: alias
          in: path
          required: true
          description: The short URL alias
          schema:
            type: string
            example: "shorty"
      responses:
        '301':
          description: Redirect to long URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  url_id:
                    type: integer
                    example: 1
                  long_url:
                    type: string
                    example: "https://example.com"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Alias must be 6 characters long"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Alias does not exist"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal Server Error"
  /api/analytics/{alias}:
    get:
      tags:
        - Analytics
      summary: Get analytics for a specific alias
      operationId: getAliasAnalytics
      parameters:
        - name: alias
          in: path
          required: true
          description: The short URL alias
          schema:
            type: string
            example: "shorty"
      responses:
        '200':
          description: Returns analytics for the alias
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_clicks:
                    type: integer
                    example: 100
                  unique_clicks:
                    type: integer
                    example: 50
                  clicks_by_date:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                          example: "2023-01-01"
                        click_count:
                          type: integer
                          example: 20
                  os_type:
                    type: array
                    items:
                      type: object
                      properties:
                        os_name:
                          type: string
                          example: "Windows"
                        unique_clicks:
                          type: integer
                          example: 30
                        unique_users:
                          type: integer
                          example: 20
                  device_type:
                    type: array
                    items:
                      type: object
                      properties:
                        device_name:
                          type: string
                          example: "Desktop"
                        unique_clicks:
                          type: integer
                          example: 40
                        unique_users:
                          type: integer
                          example: 25
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Alias must be 6 characters long"
        '404':
          description: Alias does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Alias does not exist"

  /api/analytics/topic/{topic}:
    get:
      tags:
        - Analytics
      summary: Get analytics for a specific topic
      operationId: getTopicAnalytics
      security:
        - BearerAuth: []
      parameters:
        - name: topic
          in: path
          required: true
          description: The topic to retrieve analytics for
          schema:
            type: string
            example: "Social Media"
      responses:
        '200':
          description: Returns analytics for the topic
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_clicks:
                    type: integer
                    example: 200
                  unique_clicks:
                    type: integer
                    example: 100
                  clicks_by_date:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                          example: "2023-01-01"
                        click_count:
                          type: integer
                          example: 50
                  urls:
                    type: array
                    items:
                      type: object
                      properties:
                        short_url:
                          type: string
                          example: "shorty"
                        total_clicks:
                          type: integer
                          example: 30
                        unique_users:
                          type: integer
                          example: 15
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Topic must be provided"
        '401':
          description: Unauthorized Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized request"
        '404':
          description: Topic does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Topic does not exist"

  /api/analytics/overall:
    get:
      tags:
        - Analytics
      summary: Get overall analytics for a user
      operationId: getOverallAnalytics
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Returns overall analytics for the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_urls:
                    type: integer
                    example: 10
                  total_clicks:
                    type: integer
                    example: 500
                  unique_clicks:
                    type: integer
                    example: 250
                  clicks_by_date:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                          example: "2023-01-01"
                        click_count:
                          type: integer
                          example: 100
                  os_type:
                    type: array
                    items:
                      type: object
                      properties:
                        os_name:
                          type: string
                          example: "Windows"
                        unique_clicks:
                          type: integer
                          example: 100
                        unique_users:
                          type: integer
                          example: 80
                  device_type:
                    type: array
                    items:
                      type: object
                      properties:
                        device_name:
                          type: string
                          example: "Desktop"
                        unique_clicks:
                          type: integer
                          example: 150
                        unique_users:
                          type: integer
                          example: 120
        '401':
          description: Unauthorized Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized request"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal Server Error"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
          example: 10
        user_email:
          type: string
          example: "abc@xyz.com"
    URLAnalytics:
      type: object
      properties:
        total_urls:
          type: integer
          example: 10
        total_clicks:
          type: integer
          example: 500
        unique_clicks:
          type: integer
          example: 250
        clicks_by_date:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
                example: "2023-01-01"
              click_count:
                type: integer
                example: 20
        os_type:
          type: array
          items:
            type: object
            properties:
              os_name:
                type: string
                example: "Windows"
              unique_clicks:
                type: integer
                example: 30
              unique_users:
                type: integer
                example: 20
        device_type:
          type: array
          items:
            type: object
            properties:
              device_name:
                type: string
                example: "Desktop"
              unique_clicks:
                type: integer
                example: 40
              unique_users:
                type: integer
                example: 25
        urls:
          type: array
          items:
            type: object
            properties:
              short_url:
                type: string
                example: "shorty"
              total_clicks:
                type: integer
                example: 30
              unique_users:
                type: integer
                example: 15
    URLBody:
      type: object
      properties:
        long_url:
          type: string
          example: "https://example.com"
        custom_alias:
          type: string
          example: "shorty"
        topic:
          type: string
          example: "Social Media"
      required:
        - long_url